// This will get concatentated to the end of the file generated by emscripten,
// to fix Webpack loading issues. (https://github.com/DanRuta/jsNet/issues/41)
typeof window!="undefined" && (window.Module = Module)